web:
  build: Dockerfiles/web
  command: python3 ./run.py
  ports:
    - "8080:8080"
  volumes:
    - .:/code
  links:
    - db

db:
  image: mongo:3.4.4
  volumes:
    - ./Dockerfiles/db:/backup

mongo-seed:
  build: Dockerfiles/db
  links:
    - db

