services:
  web:
    build: Dockerfiles/web
    command: python3 ./run.py
    ports:
    - "8080:8080"
    volumes:
    - .:/code
    links:
    - db

  db:
    image: mongo:latest
    volumes:
    - ./Dockerfiles/db:/backup
    ports:
      - "27017:27017"

  mongo-seed:
    build: Dockerfiles/db
    links:
    - db

